### ISSUE TITLE
CSS Restructuring

### ISSUE THREAD

**Issue by klattimer** [klattimer/SystemDashboard#18]
A new core CSS configuration which meets the following requirements 

-  root CSS vars for defining the colours used in the UI
-  CSS files for each unique display element
-  Clean up of the chart classes/ID definitions 
-  Allows over-ride base colours with theme colours
-  Allows media-query to modify the width of columns, e.g. mobile col width is 2 not 4, and therefore all the descendant calculations are up-to-scratch. Other things need to be given global properties in this way.
-  Exposes theme colours, appropriately for chart.js (may require a small javascript loader to parse them out)

**Comment by klattimer** [comment]
@LameLemon

**Comment by LameLemon** [comment]
I did see the css commit you did, definitely cleaner looking. Do you have any idea how you could specify an alternate css file to use in the config and then modify the index.html file?

**Comment by klattimer** [comment]
@LameLemon I want to use mako, a pattern which is something like;

head
 -- insert script/style tags
container
-- Insert templates

And use handlebars perhaps as a client side templating language. 

How are you getting on with the CSS, I'm likely to add some stuff fairly soon around the (incomplete) power menu.

**Comment by LameLemon** [comment]
Mako looks interesting, I'm quite busy this month, can't guarantee I'll complete anything.

**Comment by LameLemon** [comment]
So, if I'm understanding this correctly we have the HTML file and instead of the specifying the CSS file we have a variable, say `${css-file}`.  Then in Python we load this HTML has a template and enter the CSS filename through the variable `css-file` and render?

I've read through the [documentation](https://docs.makotemplates.org/en/latest/usage.html#), I'm just having trouble understanding how the template file is structured. I haven't been able to find many examples or other information around the web either.

**Comment by klattimer** [comment]
I think I've done this too
